### ISSUE TITLE
Maintaining this Library

### ISSUE THREAD

**Issue by nla-brandonjames** [marketvision/ShipStation4Net#17]
Hey contributors, I will not be maintaining this library any more since I am ending my employment with my company on July 20. Would MarketVision like to take over the reins on this project? Thanks. @mynkow @vlad-kurdesov. You guys were a great support in the development of ShipStation4Net.

**Comment by vlad-kurdesov** [comment]
Hi Brandon,

Sorry to hear about it.. Hope that it’s an opportunity for new horizons!

MarketVision would like to take over this project (if possible) – we have clients that rely on this project on production environment and we definitely plan to use this project package for future clients.

I’m not very familiar how transition is done for package projects and what would be next steps..

Thank you
Vlad

**Comment by nla-brandonjames** [comment]
I will try to take the appropriate transfer procedures as I have not done this before myself. It looks like the form for GitHub Repository Transfer requires a username or organization. So if you would prefer the ownership be transferred to MarketVision instead of an individual it appears you may do so.

**Comment by vlad-kurdesov** [comment]
Please let me know if I could assist with anything. I just checked and haven't seen any emails from github about project transfer. I removed forked copy of this repo from marketvision (just in case if it confused github anyhow). if it's possible to transfer it to organization, I would prefer that option.

I also not sure if there will be a way for us to publish updated packages to nuget (for same package). I researched, and found this article - https://blog.nuget.org/20130205/managing-package-owners.html .. we haven't created organization account in nuget.org for marketvision yet (we mostly use myget), but I have personal account there with same username as my github account (@vlad-kurdesov). I assume, if you add me as package owner (for now), I could setup CI on our side with my apiKeys to publish new versions & later on, I will be able to add marketvision organization account as owner of package (once we get it setup on nuget.org)

**Comment by nla-brandonjames** [comment]
I sent a transfer request to your username, and you will have to initiate the transfer to your organization from there. I am going to get the NuGet ownership taken care of next.

**Comment by vlad-kurdesov** [comment]
Thank you! I just accepted both
