### ISSUE TITLE
product length, width, height, weight change form int to double

### ISSUE THREAD

**Issue by angelinos** [marketvision/ShipStation4Net#24]
Hi,

In the product entities the length, width, height and weightOz is of type int.  I know in the api documentation it says it's type of number https://www.shipstation.com/docs/api/models/product/ and doesn't really specify if it's int or double.  However I can confirm that from the UI you can enter decimal values and when you do a GET product via the API it returns the decimals as well.  

Are we able to change the variable types from int to double for those fields?

Thanks

**Comment by mv-vlad-kurdesov** [comment]
hm. I wish ShipStation Api Documentation was a bit more accurate. lol
There are some fields not explained in their examples and yeah, this is one of them.
In any case, sorry for delay - this update was made and you should be able to use it in 1.0.1 version of package
