### ISSUE TITLE
Orders.GetAllPages() errors because of new insurance provider

### ISSUE THREAD

**Issue by bw3740** [marketvision/ShipStation4Net#36]
Error Message: "One or more errors occurred. (Error converting value \"parcelguard\" to type 'System.Nullable`1[ShipStation4Net.Domain.Enumerations.InsuranceOptionProviders]'. Path 'orders[88].insuranceOptions.provider', line 1, position 268260.)"

Example to reproduce error:

public List<Order> GetShipStationOrders()
        {
            var ret = new List<Order>();
            var filter = new OrdersFilter
            {
                CreateDateStart = DateTime.Now.AddDays(-90),
                CreateDateEnd = DateTime.Now
            };

            var pages = _shipStationClient.Orders.GetAllPages(filter);
            foreach (var page in pages)
            {
                ret.AddRange(page);
            }

            return ret;
        }

**Comment by mv-vlad-kurdesov** [comment]
`xcover` & `parcelguard` insurance provider options were added in 1.0.5 package
changes: https://github.com/marketvision/ShipStation4Net/commit/242e5778e79a8ac6aa1acc0a4676c027a8cbb624

**Comment by bw3740** [comment]
Thanks! You had that fixed before I even had time to pull the code.
