### ISSUE TITLE
Issue Getting Async Data

### ISSUE THREAD

**Issue by BenDirectPromos** [marketvision/ShipStation4Net#37]
Very strange issue. On any call to get data, I get no expectations and it just fails out to calling method.

**Comment by BenDirectPromos** [comment]
And this working yesterday

**Comment by mv-vlad-kurdesov** [comment]
We have this integration on production environment for multiple clients atm and no issues.
Most likely something is off with your setup. You would need to provide more details

**Comment by BenDirectPromos** [comment]
I figured it out, the calling method was not async and I things were not working correctly, once I fixed the all was good.

Sorry for the trouble. Hopefully this helps someone else in future.
