### ISSUE TITLE
Client interfaces are not able to be mocked

### ISSUE THREAD

**Issue by mkercheval-tva** [marketvision/ShipStation4Net#40]
Unable to mock client interfaces due to their internal nature, hindering unit testing. Recommend making interfaces public for mockability and improved testability.

**Comment by mv-vlad-kurdesov** [comment]
If you want to update implementation to support it, i can review and merge it
i will not be doing significant rewrite of this library - sorry

**Comment by mv-vlad-kurdesov** [comment]
1.0.7 should be available in next 10-15min

**Comment by mkercheval-tva** [comment]
SOLID. Thank you
