### ISSUE TITLE
OverflowException: Value was either too large or too small for an Int32.

### ISSUE THREAD

**Issue by BenDirectPromos** [marketvision/ShipStation4Net#44]
Getting the following error when calling Orders.GetAllPagesAsync

Newtonsoft.Json.JsonReaderException: 'Could not convert to integer: 1202147746409. Path 'orders[10].items[0].orderItemId', line 1, position 26119.'

OverflowException: Value was either too large or too small for an Int32.

**Comment by mv-vlad-kurdesov** [comment]
1.0.9 will have fix for it - type was changed to long (#45 )
whatever ShipStation changed, it just started to fail recently
