### ISSUE TITLE
The insuranceCost in ShipmentLabel has changed

### ISSUE THREAD

**Issue by atifali7** [marketvision/ShipStation4Net#48]
Hi,

The type of variable in "insuranceCost" in ShipmentLabel object has changed from int to decimal. At the moment the latest version is showing error. 

Please update and post new version.

Thanks
Muhammad

**Comment by atifali7** [comment]
Updated project added here for approval. thanks
[ShipStation4Net-master.zip](https://github.com/user-attachments/files/15848288/ShipStation4Net-master.zip)

**Comment by mv-vlad-kurdesov** [comment]
will be fixed in 1.0.12
I checked their documentation and there is not a single place where type is specified :( and in examples it is shows as 0..
I changed it to double to match another place where we have it
